In [1]:
# Importing the libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [2]:
# Importing the dataset
dataset = pd.read_csv('preprocessed-Flipkart Mobile.csv')
dataset= pd.get_dummies(dataset, drop_first=True)
X = dataset.drop('sales_price', axis=1)
y = dataset['sales_price']

In [3]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [4]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [5]:
# Applying RFE
from sklearn.feature_selection import RFE
from sklearn.ensemble import RandomForestClassifier
rf= RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
rfe =RFE(estimator=rf, n_features_to_select=5)
X_train = rfe.fit_transform(X_train, y_train)
X_test = rfe.transform(X_test)

In [6]:
# Fitting Logistic Regression to the Training set
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
param_grid={'n_estimators' :[100], 'criterion':['gini', 'entropy', 'log_loss'],
           'max_features':['sqrt', 'log2'], 'class_weight':['balanced', 'balanced_subsample']}


grid=GridSearchCV(RandomForestClassifier(),param_grid,refit=True,verbose=3,n_jobs=-1,scoring='f1_weighted')
grid.fit(X_train,y_train)
re=grid.cv_results_
y_predict=grid.predict(X_test)
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_predict)
from sklearn.metrics import classification_report
clf_report = classification_report(y_test,y_predict)
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,y_predict,average='weighted')
print("The f1 macro value the best parameter{}:".format(grid.best_params_),f1_macro)

Fitting 5 folds for each of 12 candidates, totalling 60 fits


C:\Users\ADMIN\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:725: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(


The f1 macro value the best parameter{'class_weight': 'balanced_subsample', 'criterion': 'gini', 'max_features': 'sqrt', 'n_estimators': 100}: 0.652457039084946


C:\Users\ADMIN\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ADMIN\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ADMIN\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ADMIN\anaconda3\Lib\site-packages\sklearn\metrics\_cla

In [7]:
print(cm)

[[0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [0 0 2 ... 0 0 0]
 ...
 [0 0 0 ... 2 0 0]
 [0 0 0 ... 0 3 0]
 [0 0 0 ... 0 0 9]]


In [8]:
from sklearn.metrics import classification_report
clf_report = classification_report(y_test,y_predict)

C:\Users\ADMIN\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ADMIN\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ADMIN\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ADMIN\anaconda3\Lib\site-packages\sklearn\metrics\_cla

In [9]:
print(clf_report)

              precision    recall  f1-score   support

        6499       0.00      0.00      0.00         0
        6999       0.00      0.00      0.00         1
        7499       1.00      0.67      0.80         3
        7999       0.25      1.00      0.40         1
        8190       0.00      0.00      0.00         1
        8252       0.00      0.00      0.00         1
        8499       1.00      1.00      1.00         1
        8850       0.00      0.00      0.00         1
        8999       0.00      0.00      0.00         2
        9499       1.00      1.00      1.00         2
        9999       1.00      1.00      1.00         1
       10099       0.00      0.00      0.00         0
       10499       0.00      0.00      0.00         0
       10999       1.00      1.00      1.00         1
       11490       0.00      0.00      0.00         0
       11499       0.62      1.00      0.77         5
       11599       0.67      1.00      0.80         2
       11799       0.00    

In [ ]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

In [11]:
table=pd.DataFrame.from_dict(re)
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0        0.535657      0.010987         0.033457        0.003367   
1        0.529567      0.012678         0.037453        0.005879   
2        0.593983      0.005021         0.031143        0.001324   
3        0.597104      0.006204         0.029090        0.004860   
4        0.874146      0.059361         0.047855        0.001223   
5        0.963244      0.029837         0.057735        0.010844   
6        1.084057      0.013249         0.052596        0.003477   
7        1.107014      0.041265         0.062975        0.011069   
8        1.320118      0.023382         0.058996        0.004873   
9        1.292141      0.096700         0.052598        0.006176   
10       1.275045      0.110713         0.061596        0.007232   
11       1.214604      0.098295         0.053034        0.008076   

    param_class_weight param_criterion param_max_features param_n_estimators  \
0             balanced            gini               sqrt                100   
1             balanced            gini               log2                100   
2             balanced         entropy               sqrt                100   
3             balanced         entropy               log2                100   
4             balanced        log_loss               sqrt                100   
5             balanced        log_loss               log2                100   
6   balanced_subsample            gini               sqrt                100   
7   balanced_subsample            gini               log2                100   
8   balanced_subsample         entropy               sqrt                100   
9   balanced_subsample         entropy               log2                100   
10  balanced_subsample        log_loss               sqrt                100   
11  balanced_subsample        log_loss               log2                100   

                                               params  split0_test_score  \
0   {'class_weight': 'balanced', 'criterion': 'gin...           0.622291   
1   {'class_weight': 'balanced', 'criterion': 'gin...           0.622291   
2   {'class_weight': 'balanced', 'criterion': 'ent...           0.621153   
3   {'class_weight': 'balanced', 'criterion': 'ent...           0.608397   
4   {'class_weight': 'balanced', 'criterion': 'log...           0.621153   
5   {'class_weight': 'balanced', 'criterion': 'log...           0.625811   
6   {'class_weight': 'balanced_subsample', 'criter...           0.624707   
7   {'class_weight': 'balanced_subsample', 'criter...           0.623188   
8   {'class_weight': 'balanced_subsample', 'criter...           0.621256   
9   {'class_weight': 'balanced_subsample', 'criter...           0.608592   
10  {'class_weight': 'balanced_subsample', 'criter...           0.613423   
11  {'class_weight': 'balanced_subsample', 'criter...           0.622119   

    split1_test_score  split2_test_score  split3_test_score  \
0            0.621199           0.675592           0.658512   
1            0.631884           0.670761           0.651208   
2            0.613470           0.670531           0.670531   
3            0.621551           0.664320           0.660870   
4            0.600295           0.660455           0.643933   
5            0.621199           0.648447           0.626087   
6            0.643961           0.677790           0.661410   
7            0.640097           0.670761           0.657897   
8            0.609956           0.654589           0.647343   
9            0.609956           0.654244           0.652979   
10           0.613470           0.674948           0.656844   
11           0.600426           0.649827           0.659903   

    split4_test_score  mean_test_score  std_test_score  rank_test_score  
0            0.709804         0.657480        0.033530                3  
1            0.706373         0.656503        0.029983                4  
2            0.704412         0.656019        0

In [12]:
import pickle
filename="DIMON_final_model.sav"
pickle.dump(grid,open(filename,'wb'))
loaded_model=pickle.load(open("DIMON_final_model.sav",'rb'))


In [13]:
X

ROM  RAM  display_size  num_rear_camera  battery_capacity  ratings  \
0     64    2           6.0                1              2500     4.50   
1     64    4           6.0                2              2815     4.50   
2     64    2           6.0                1              2500     4.50   
3     64    3           6.1                1              2942     4.55   
4    128    4           6.1                2              2815     4.55   
..   ...  ...           ...              ...               ...      ...   
425   32    3           6.0                2              4000     4.30   
426   64    4           6.0                2              4000     4.30   
427  128    6           6.5                3              4250     4.20   
428   32    3           6.2                2              5000     4.20   
429   32    3           6.0                2              4000     4.30   

     discount_percent     sales  brand_Poco  brand_Realme  ...  \
0                0.17  71.83375       False         False  ...   
1                0.04   1.39000       False         False  ...   
2                0.17  71.83375       False         False  ...   
3                0.10  23.07000       False         False  ...   
4                0.02   5.15000       False         False  ...   
..                ...       ...         ...           ...  ...   
425              0.30   1.50000       False         False  ...   
426              0.28   1.73000       False         False  ...   
427              0.12   3.42000       False         False  ...   
428              0.07   6.77000       False         False  ...   
429              0.31   1.53000       False         False  ...   

     processor_Exynos  processor_MediaTek  processor_Others  \
0               False               False             False   
1               False               False             False   
2               False               False             False   
3               False               False             False   
4               False               False             False   
..                ...                 ...               ...   
425             False               False             False   
426             False               False             False   
427             False               False             False   
428             False               False             False   
429             False               False             False   

     processor_Qualcomm  processor_Water  processor_iOS  screen_size_Medium  \
0                 False             True          False               False   
1                 False            False          False               False   
2                 False             True          False               False   
3                 False            False           True                True   
4                 False            False          False                True   
..                  ...              ...            ...                 ...   
425                True            False          False               False   
426                True            False          False               False   
427                True            False          False               False   
428                True            False          False                True   
429                True            False          False               False   

     screen_size_Small  screen_size_Very Large  screen_size_Very Small  
0                False                   False                    True  
1                 True                   False                   False  
2                False                   False                    True  
3                False                   False                   False  
4                False                   False                   False  
..                 ...                     ...                     ...  
425               True                   False                   False  
426               Tru

In [16]:
display_size_input = float(input("display_size : "))
num_rear_camera_input = float(input("num_rear_camera : "))
battery_capacity_input = float(input("battery_capacity : "))
ratings_input = float(input("ratings : "))
sales_input = float(input("sales : "))


display_size : 4
num_rear_camera : 3.5
battery_capacity : 5633
ratings : 7.3
sales : 5200


In [17]:
future_Prediction=loaded_model.predict([[display_size_input,num_rear_camera_input,battery_capacity_input,ratings_input,sales_input]])
# change the paramter,play with it.
print("Future_Prediction={}".format(future_Prediction))

Future_Prediction=[25999]
